#include "x.hpp"
#include <algorithm>
#include <charconv>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>
namespace x{namespace{double R(double x,std::uint8_t q){double f=std::pow(10.,q);return(x>=0?std::floor(x*f+.500000001):std::ceil(x*f-.500000001))/f;}d D(b const&x){return x.v>=0?d::U:d::D;}double P(b const&x,double p,d z){double v=std::clamp((p-x.l)/(x.h-x.l),0.,1.);return z==d::U?1-v:v;}std::optional<double>N(std::string_view s,std::string_view k){auto x=s.find(k);if(x==s.npos)return{};x=s.find(':',x+k.size());if(x==s.npos)return{};++x;while(x<s.size()&&(s[x]==' '||s[x]=='"'))++x;double v{};auto[a,e]=std::from_chars(s.data()+x,s.data()+s.size(),v);return e==std::errc{}?std::optional<double>(v):std::nullopt;}}
void c::i0(double p)noexcept{auto a=g();for(std::size_t x=0;x<n;++x){double h=R(p,q.q);b[x]={h,R(h-a[x]*q.p,q.q),a[x]};f[x]={1,0,0,p,d::U};this->p[x].reset();}o=1;l=p;k=1;}bool c::u(double p)noexcept{if(!o||!std::isfinite(p))return{};double h=std::max(p,l),l=std::min(p,this->l);auto a=g();bool o{};for(std::size_t x=0;x<n;++x){auto&v=b[x];auto z=D(v);double r=a[x]*q.p;bool H=h>v.h,L=l<v.l;if(H&&L){if(h-v.h>=v.l-l)v={h,h-r,a[x]};else v={l+r,l,-a[x]};}else if(H)v={h,h-r,a[x]};else if(L)v={l+r,l,-a[x]};o|=z!=D(v);auto&F=f[x];double P0=std::clamp((p-v.l)/(v.h-v.l),0.,1.),V=F.v;F.v=V*.65+(P0-F.p)*.35;F.a=F.v-V;F.p=P0;double r0=std::max(r*.12,q.p*2);if(F.z==d::U){if(p>=F.e)F.e=p;else if(F.e-p>=r0){this->p[x]={x,d::U,F.e,p};F.z=d::D;F.e=p;}}else if(p<=F.e)F.e=p;else if(p-F.e>=r0){this->p[x]={x,d::D,F.e,p};F.z=d::U;F.e=p;}}this->l=p;++k;return o;}
i q(const std::string&p)noexcept{return p.size()>2&&p.substr(p.size()-3)=="JPY"?i{.001,3}:p=="XAUUSD"?i{.01,2}:p=="BTCUSD"?i{.1,1}:i{};}std::vector<a>r(const std::filesystem::path&p){std::ifstream f(p);if(!f)throw std::runtime_error("open");std::vector<a>v;std::string s;while(std::getline(f,s)){auto t=N(s,"\"t\""),o=N(s,"\"o\""),h=N(s,"\"h\""),l=N(s,"\"l\""),c=N(s,"\"c\"");if(t&&o&&h&&l&&c)v.push_back({(std::int64_t)*t,*o,*h,*l,*c});}return v;}std::vector<s>r(std::vector<a>const&v,c&x){std::vector<s>w;w.reserve(v.size()*3);for(auto const&z:v){if(!x.o)x.i0(z.o);for(auto[p,q]:{std::pair{20000LL,z.h},{40000LL,z.l},{59000LL,z.c}}){x.u(q);w.push_back({z.t+p,q,x.b});}}return w;}void w(const std::filesystem::path&p,std::vector<s>const&v){std::filesystem::create_directories(p.parent_path());std::ofstream o(p);o<<std::setprecision(12);for(auto const&x:v){o<<"{\"timestamp\":"<<x.t<<",\"price\":"<<x.p<<",\"boxes\":[";for(std::size_t i=0;i<n;++i){if(i)o<<',';auto const&b=x.b[i];o<<"{\"high\":"<<b.h<<",\"low\":"<<b.l<<",\"value\":"<<b.v<<'}';}o<<"]}\n";}}
std::uint32_t z(std::vector<double>const&v)noexcept{int p{};std::uint32_t n{};bool o{};for(auto x:v){if(!x)continue;o=1;int s=x>0?1:-1;if(p&&p!=s)++n;p=s;}return o?std::max(1u,n/2):0;}j m::u(s const&x){if(++k<24)return{k::A,"warm"};auto a0=c::g();std::size_t i{};double e=1e9;for(std::size_t x=0;x<n;++x)if(auto v=std::abs(a0[x]-30);v<e)e=v,i=x;auto const&b=x.b[i];d z=b.v>=0?d::U:d::D;double p=P(b,x.p,z);if(!a.o||a.z!=z||a.h!=b.h||a.l!=b.l){if(p>=.9)a={z,b.h,b.l,p,1};return{k::A,"arm"};}bool o=a.p>.8&&p<=.8;a.p=p;if(!o)return{k::A,"wait"};a.o=0;if(p<.75)return{k::A,"skip"};double r=b.h-b.l;return z==d::U?j{k::L,"go",x.p,b.l,x.p+2*r,i}:j{k::S,"go",x.p,b.h,x.p-2*r,i};}
e::e(std::string p):p(std::move(p)),q(x::q(this->p)),c0(q),m0(q){}bool e::b(const std::filesystem::path&p){try{auto v=r(p);if(v.empty())return{};for(auto const&x:r(v,c0))m0.u(x);o=1;return 1;}catch(...){return{};}}j e::u(std::int64_t t,double b,double a){if(!o||!std::isfinite(b)||!std::isfinite(a)||b<=0||a<b)return{k::A,"bad"};if(b==l)return{k::A,"dup"};l=b;c0.u(b);return m0.u({t,b,c0.b});}std::string e::g()const{std::ostringstream x;x<<"{\"pair\":\""<<p<<"\",\"bootstrapped\":"<<(o?"true":"false")<<",\"lastPrice\":"<<l<<"}";return x.str();}}
