#include "x.hpp"
#include "p.hpp"
#include <algorithm>
#include <charconv>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>
namespace x{namespace{double R(double x,std::uint8_t q){double f=std::pow(10.,q);return(x>=0?std::floor(x*f+.500000001):std::ceil(x*f-.500000001))/f;}d D(b const&x){return x.v>=0?d::U:d::D;}std::optional<double>N(std::string_view s,std::string_view k){auto x=s.find(k);if(x==s.npos)return{};x=s.find(':',x+k.size());if(x==s.npos)return{};++x;while(x<s.size()&&(s[x]==' '||s[x]=='"'))++x;double v{};auto[a,e]=std::from_chars(s.data()+x,s.data()+s.size(),v);return e==std::errc{}?std::optional<double>(v):std::nullopt;}}
void c::i0(double p)noexcept{auto a=g();for(std::size_t x=0;x<n;++x){double h=R(p,q.q);b[x]={h,R(h-a[x]*q.p,q.q),a[x]};f[x]={1,0,0,p,d::U};this->p[x].reset();}o=1;l=p;k=1;}bool c::u(double p)noexcept{if(!o||!std::isfinite(p))return{};double h=std::max(p,l),l=std::min(p,this->l);auto a=g();bool o{};for(std::size_t x=0;x<n;++x){auto&v=b[x];auto z=D(v);double r=a[x]*q.p;bool H=h>v.h,L=l<v.l;if(H&&L){if(h-v.h>=v.l-l)v={h,h-r,a[x]};else v={l+r,l,-a[x]};}else if(H)v={h,h-r,a[x]};else if(L)v={l+r,l,-a[x]};o|=z!=D(v);auto&F=f[x];double P0=std::clamp((p-v.l)/(v.h-v.l),0.,1.),V=F.v;F.v=V*.65+(P0-F.p)*.35;F.a=F.v-V;F.p=P0;double r0=std::max(r*.12,q.p*2);if(F.z==d::U){if(p>=F.e)F.e=p;else if(F.e-p>=r0){this->p[x]={x,d::U,F.e,p};F.z=d::D;F.e=p;}}else if(p<=F.e)F.e=p;else if(p-F.e>=r0){this->p[x]={x,d::D,F.e,p};F.z=d::U;F.e=p;}}this->l=p;++k;return o;}
i q(const std::string&p)noexcept{return p.size()>2&&p.substr(p.size()-3)=="JPY"?i{.001,3}:p=="XAUUSD"?i{.01,2}:p=="BTCUSD"?i{.1,1}:i{};}std::vector<a>r(const std::filesystem::path&p){std::ifstream f(p);if(!f)throw std::runtime_error("open");std::vector<a>v;std::string s;while(std::getline(f,s)){auto t=N(s,"\"t\""),o=N(s,"\"o\""),h=N(s,"\"h\""),l=N(s,"\"l\""),c=N(s,"\"c\"");if(t&&o&&h&&l&&c)v.push_back({(std::int64_t)*t,*o,*h,*l,*c});}return v;}std::vector<s>r(std::vector<a>const&v,c&x){std::vector<s>w;w.reserve(v.size()*3);for(auto const&z:v){if(!x.o)x.i0(z.o);for(auto[p,q]:{std::pair{20000LL,z.h},{40000LL,z.l},{59000LL,z.c}}){x.u(q);w.push_back({z.t+p,q,x.b});}}return w;}void w(const std::filesystem::path&p,std::vector<s>const&v){std::filesystem::create_directories(p.parent_path());std::ofstream o(p);o<<std::setprecision(12);for(auto const&x:v){o<<"{\"timestamp\":"<<x.t<<",\"price\":"<<x.p<<",\"boxes\":[";for(std::size_t i=0;i<n;++i){if(i)o<<',';auto const&b=x.b[i];o<<"{\"high\":"<<b.h<<",\"low\":"<<b.l<<",\"value\":"<<b.v<<'}';}o<<"]}\n";}}
std::uint32_t z(std::vector<double>const&v)noexcept{int p{};std::uint32_t n{};bool o{};for(auto x:v){if(!x)continue;o=1;int s=x>0?1:-1;if(p&&p!=s)++n;p=s;}return o?std::max(1u,n/2):0;}
using Z=std::unordered_map<int,std::vector<std::vector<int>>>;static Z const&A(){static Z m=[]{Z m;for(char const*p=x::P;p&&*p;){char*q;int k=std::strtol(p,&q,10);if(*q!=':')break;p=q+1;auto&v=m[k];while(*p&&*p!='|'){std::vector<int>a;while(*p&&*p!=';'&&*p!='|'){a.push_back(std::strtol(p,&q,10));p=q;if(*p==',')++p;}if(!a.empty())v.push_back(std::move(a));if(*p==';')++p;}if(*p=='|')++p;}return m;}();return m;}
static void W(int k,std::vector<int>&p,std::unordered_set<int>const&s,std::vector<std::vector<int>>&o){auto i=A().find(std::abs(k));if(i==A().end()){if(!p.empty()&&std::abs(p.back())==10)o.push_back(p);return;}for(auto const&r:i->second){std::vector<int>a;a.reserve(r.size());for(auto x:r)a.push_back(k>0?x:-x);bool ok=1;for(auto x:a)ok&=s.contains(x);if(!ok)continue;int l=a.back();if(a.size()==1&&std::abs(l)==std::abs(k)){if(!p.empty()&&std::abs(p.back())==10)o.push_back(p);continue;}auto z=p.size();p.insert(p.end(),a.begin(),a.end());if(std::abs(l)==std::abs(k)){if(std::abs(p.back())==10)o.push_back(p);}else W(l,p,s,o);p.resize(z);}}
static unsigned L(std::vector<int>const&p){unsigned l{};std::size_t i{};int k=p.empty()?0:p[0];while(i+1<p.size()){auto z=A().find(std::abs(k));if(z==A().end())break;bool o{};for(auto const&r:z->second){std::vector<int>a;for(auto x:r)a.push_back(k>0?x:-x);auto e=i+1+a.size();if(e<=p.size()&&std::equal(a.begin(),a.end(),p.begin()+i+1)){++l;i=e-1;k=a.back();o=1;break;}}if(!o)break;}return std::max(1u,l);}
std::vector<j>m::a(s const&x)const{std::vector<int>v;std::unordered_set<int>z;for(auto const&b:x.b){auto q=(int)std::llround(b.v/this->q.p);v.push_back(q);z.insert(q);}std::vector<std::vector<int>>p;for(int k:{1000,866,750,650,563,488,422,366})if(z.contains(k)){std::vector<int>a{k};W(k,a,z,p);}std::vector<j>o;for(auto const&a:p){auto l=L(a);if(l<3||l>6)continue;bool u=a[0]>0;std::vector<std::pair<int,b const*>>d;for(auto n:a)for(std::size_t i=0;i<v.size();++i)if(v[i]==n){if((u&&n>0)||(!u&&n<0))d.push_back({n,&x.b[i]});break;}std::sort(d.begin(),d.end(),[](auto const&a,auto const&b){return std::abs(a.first)>std::abs(b.first);});if(d.size()<=l)continue;auto e=u?d[l].second->h:d[l].second->l;auto t=u?d[l-1].second->l:d[l-1].second->h;auto r=d[0].second->h-d[0].second->l;auto g=u?d[0].second->h+r/4:d[0].second->l-r/4;if(std::isfinite(e)&&std::isfinite(t)&&std::isfinite(g)&&std::abs(e-t)>0&&((u&&g>e)||(!u&&g<e)))o.push_back({u?k::L:k::S,"pattern",e,t,g,0,a,l});}std::sort(o.begin(),o.end(),[](j const&a,j const&b){return a.l>b.l||(a.l==b.l&&a.p.size()>b.p.size());});return o;}j m::u(s const&x)const{auto a=this->a(x);return a.empty()?j{k::A,"none"}:a.front();}
static double M(i q){return q.p==.01?100.:1./(q.p*10.);}static std::string I(std::string const&p,j const&d){std::ostringstream x;x<<p<<'_'<<(int)d.k<<'_'<<d.x<<'_'<<d.s<<'_'<<d.t;return x.str();}
e::e(std::string p):p(std::move(p)),q(x::q(this->p)),c0(q),m0(q){if(auto x=std::getenv("MULTI_WAVE_BALANCE"))B=std::atof(x);if(auto x=std::getenv("MULTI_WAVE_RISK_DIVISOR"))R=std::max(1.,std::atof(x));if(auto x=std::getenv("MULTI_WAVE_MAX_SPREAD_PIPS"))X=std::max(0.,std::atof(x));P=std::getenv("MULTI_WAVE_LOG_DIR")?std::getenv("MULTI_WAVE_LOG_DIR"):std::string("data/pairs/")+this->p;}
void e::L(char const*n,std::string const&s){std::filesystem::create_directories(P);std::ofstream o(P/(std::string(n)+".jsonl"),std::ios::app);o<<s<<'\n';}
void e::T(std::int64_t t,double b,double a){for(auto&i:v)if(i.x){double p=i.d==k::L?b:a,g=(i.d==k::L?p-i.e:i.e-p)*M(q);if(g>i.m)i.m=g;if((i.d==k::L&&p<=i.s)||(i.d==k::S&&p>=i.s)||(i.d==k::L&&p>=i.t)||(i.d==k::S&&p<=i.t)){bool w=(i.d==k::L?p>=i.t:p<=i.t);i.x=0;i.c=t;z.erase(i.l);++C;L("trades",std::string("{\"event\":\"closed\",\"id\":\"")+i.i+"\",\"reason\":\""+(w?"target":"stop")+"\",\"exit\":"+std::to_string(p)+",\"pips\":"+std::to_string(g)+",\"maxPips\":"+std::to_string(i.m)+",\"timestamp\":"+std::to_string(t)+"}");}}}
j e::O(std::int64_t t,j d,double b,double a){if(d.k==k::A)return d;++S;auto l=I(p,d);L("signals",std::string("{\"event\":\"signal\",\"id\":\"")+l+"\",\"side\":"+(d.k==k::L?"\"LONG\"":"\"SHORT\"")+",\"entry\":"+std::to_string(d.e)+",\"stop\":"+std::to_string(d.s)+",\"target\":"+std::to_string(d.t)+",\"timestamp\":"+std::to_string(t)+"}");double sp=(a-b)*M(q);if(sp>X){d.r="spread";L("execution",std::string("{\"event\":\"rejected\",\"id\":\"")+l+"\",\"reason\":\"spread\"}");return d;}if(z.contains(l)){d.r="lock";L("execution",std::string("{\"event\":\"rejected\",\"id\":\"")+l+"\",\"reason\":\"lock\"}");return d;}double e=d.k==k::L?a:b,r=std::abs(e-d.s)*M(q),o=std::floor((B/R)/(r*10.)*100.)/100.;if(!std::isfinite(r)||r<=0||o<.01){d.r="risk";L("execution",std::string("{\"event\":\"rejected\",\"id\":\"")+l+"\",\"reason\":\"risk\"}");return d;}if((d.k==k::L&&(d.s>=e||d.t<=e))||(d.k==k::S&&(d.s<=e||d.t>=e))){d.r="geometry";return d;}h h{p+"_"+std::to_string(++N),l,d.k,e,d.s,d.t,o,0,t,0,1,1};v.push_back(h);z.insert(l);++Q;L("trades",std::string("{\"event\":\"opened\",\"id\":\"")+h.i+"\",\"signalId\":\""+l+"\",\"side\":"+(d.k==k::L?"\"LONG\"":"\"SHORT\"")+",\"entry\":"+std::to_string(e)+",\"stop\":"+std::to_string(d.s)+",\"target\":"+std::to_string(d.t)+",\"lots\":"+std::to_string(o)+",\"timestamp\":"+std::to_string(t)+"}");L("execution",std::string("{\"event\":\"paper_open\",\"id\":\"")+h.i+"\",\"accepted\":true}");d.e=e;d.r="opened";return d;}
bool e::b(const std::filesystem::path&p){try{auto v=r(p);if(v.empty())return{};for(auto const&x:r(v,c0))m0.u(x);o=1;return 1;}catch(...){return{};}}j e::u(std::int64_t t,double b,double a){if(!o||!std::isfinite(b)||!std::isfinite(a)||b<=0||a<b)return{k::A,"bad"};T(t,b,a);if(b==l)return{k::A,"dup"};l=b;c0.u(b);return O(t,m0.u({t,b,c0.b}),b,a);}std::string e::g()const{std::ostringstream x;x<<"{\"pair\":\""<<p<<"\",\"bootstrapped\":"<<(o?"true":"false")<<",\"lastPrice\":"<<l<<",\"signals\":"<<S<<",\"opened\":"<<Q<<",\"closed\":"<<C<<",\"active\":"<<std::count_if(v.begin(),v.end(),[](auto const&x){return x.x;})<<"}";return x.str();}}
